### ISSUE TITLE
wanted: bindable TextScrollList

### ISSUE THREAD

**Issue by theodox** [theodox/mGui#20]
The default TextScrollList is just the maya one, which does not allow bulk set of items.  Need to come up with a property wrapper that allows binding to a collection and under the hood deletes and rebuilds the collection without making user do that every time.

**Comment by kartikg3** [comment]
Can you show a pseudo/example usage?

**Comment by theodox** [comment]
This is still worth doing, it should be easy...

**Comment by theodox** [comment]
In
