### ISSUE TITLE
mGui\examples\simple.py Error

### ISSUE THREAD

**Issue by mambo4** [theodox/mGui#39]
testing example files:
executing 
	\mGui\examples\simple.py
produces
	# Error: AttributeError: file <maya console> line 46: 'module' object has no attribute 'HorizontalStretchForm' # 

It seems mGui.Forms is not being imported. There are a few other forms objects referenced in the code.

**Comment by theodox** [comment]
Good catch, I have to decide whether to fix the imports in `gui` or add a separate import of `forms`
You can fix it with "from mGui.forms import *" and then removing the `gui.` from in front of the Forms in the example

**Comment by mambo4** [comment]
Would You like me too make that fix, and push it to the repo?

**Comment by theodox** [comment]
By all means! Submit a pull request when you've got it done
