### ISSUE TITLE
Add QTPy support

### ISSUE THREAD

**Issue by theodox** [theodox/mGui#63]
If we're going to keep things like the `mGui.qt` going forward we'll need to transparently support post Maya 2017.  I think [QTpy](https://pypi.python.org/pypi/QtPy) is the likeliest way forward. Thoughts?

**Comment by bob-white** [comment]
Makes sense to me
Looks like [QtPy doesn't support PySide2](https://github.com/spyder-ide/qtpy/pull/84) yet, but they are working on it.
[Qt.py](https://github.com/mottosso/Qt.py) does support PySide2 though.

Would we want to vendor a copy of the library somewhere in mGui.qt, or should we leave it as an outside install similar to pyyaml with menu_loader?

**Comment by theodox** [comment]
I'd like to keep the dependencies to a minimum,  given how annoying maya python distribution is.   It's actually part of the reason I was thinking of copying Yaml for the shelf loader...

**Comment by bob-white** [comment]
Pip basically does that, they keep a _vendor package where they keep all third party dependencies.
https://github.com/pypa/pip/tree/master/pip/_vendor

**Comment by bob-white** [comment]
Also looking through both libraries, neither has a solution for shiboken(2) vs sip.
Qt.py seems to ignore it altogether, and QTpy only has references to sip. And only for setting some API flags.
So both are incomplete for our particular needs.

**Comment by theodox** [comment]
Relevant? https://fredrikaverpil.github.io/2016/07/25/dealing-with-maya-2017-and-pyside2/

**Comment by theodox** [comment]
and  https://github.com/mottosso/Qt.py/issues/53

**Comment by theodox** [comment]
also, I'm not averse to redoing the QTextBox class a different way if that takes Shiboken out of the equation...

**Comment by bob-white** [comment]
So I was taking a look at how pymel ends up handling this problem, as they seem to avoid any direct usage of Qt related elements as well.
They basically wrote a set of functions, one for each of the Qt-bindings, that you can hand a gui object to and get back the `QWidget`. They then have some simple import checks to determine which binding you have available, and defer all calls to the appropriate function.

With something like that we could just do the following:
```python

from mGui.core.controls import TextField
from mGui.qt._utils import get_qobject


class QTextField(TextField):
    """
    A wrapper around the QTextEdit in a Maya TextField.  The main difference is that it
    can emit events on every text change
    """

    def __init__(self, key=None, **kwargs):
        super(QTextField, self).__init__(key, **kwargs)
        self.textChanged.data['qWidget'] = get_qobject(self.widget)
```

**Comment by theodox** [comment]
I'm all in favor of minimizing external dependencies... watching the QT4/QT5 nonsense from afar has confirmed all my prejudices

**Comment by bob-white** [comment]
So I've started fleshing out an initial implementation.
I'll add a branch for it either tonight or tomorrow after some more testing.

**Comment by theodox** [comment]
Closing this now that there's a PR
