### ISSUE TITLE
Data driven shelves

### ISSUE THREAD

**Issue by theodox** [theodox/mGui#64]
It would be nice to have something akin to `mGui.menuloader` for shelves, allowing good support for data-driven shelves

**Comment by bob-white** [comment]
I've made a version of this in the past using regular dictionaries and pymel/cmds. 

Do we need to be able to serialize the shelf back into a yaml string? Or is this one-way?

**Comment by theodox** [comment]
I was thinking one-way, like the way menuLoader works.  It's easy for people who want private shelves to make their own, I was thinking of these for team shelves

**Comment by bob-white** [comment]
If I were to add an example, would it make more sense to include an actual `.yaml` file, or should I just have the string in the example module?

**Comment by bob-white** [comment]
#67 wraps this guy up.
