### ISSUE TITLE
cleanup: helpers/controls and helpers/tools

### ISSUE THREAD

**Issue by theodox** [theodox/mGui#77]
these files look almost identical, and `controls` is in a wierd state. Safe to delete?

**Comment by bob-white** [comment]
`tools` looks like it's missing the `generate_panels` function and `PanelInfo` class, but yeah otherwise they look pretty much the same to me.

I think if we merged those over `tools` nuking `controls` should be safe.

**Comment by theodox** [comment]
https://github.com/theodox/mGui/tree/fix_tools

**Comment by theodox** [comment]
should be closed in #79
