### ISSUE TITLE
recursive application of `wrap()`?

### ISSUE THREAD

**Issue by theodox** [theodox/mGui#80]
Relating to the earlier discussion #77 -- should we extend the strategy in #79 for getting wrapped editors from wrapped panels so that all wrapped mGui controls recursively generate wrapped children?  What pros and cons there?

**Comment by theodox** [comment]
Apart from parent/child relationships, what other gui objects need to return wrappers from their flags?

**Comment by bob-white** [comment]
`popupMenuArray` is one culprit, it's on all `Control` instances.
`childArray` is on all `Layout` instances
`menuArray` is on `Window` and `MenuBarLayout`
`collectionItemArray` on `RadioCollection` and `ToolCollection`
`itemListLong` and `itemListShort` on `OptionMenu`

**Comment by theodox** [comment]
- [ ]  popupMenuArray 
- [ ] childArray 
- [ ] menuArray 
- [ ] itemListLong 

add more hiere as we find

**Comment by theodox** [comment]
I've been thinking this one over and I'm less concerned with it... returning wrapped items is a lot of work to do everywhere particularly because of the complexities of wrapping callbacks.
thoughts?

**Comment by bob-white** [comment]
Yeah, given the pre-existing callback complexity it might be one of those 'would be nice' ideas that we just hold in reserve until we come up with a less insane way of handling it.

**Comment by theodox** [comment]
OK, retiring this one
