### ISSUE TITLE
Problem instantiating menus with menu_loader.py

### ISSUE THREAD

**Issue by theodox** [theodox/mGui#85]
Original report here:

> am trying to run mGui.menu_loader with a yaml file, copying the example you show in your post, 
> and yet I can't.
> I have the error
>  `Error: AttributeError: file D:\packages\mayaBase\mGui\menu_loader.py line 173: 'str' object has no attribute 'instantiate' `
> Maybe I forgot something ...
> I have the latest Pyyaml version installed (3.12)

The disqus link for the blog post this was attached to is busted, so creating this for tracking.

**Comment by theodox** [comment]
Here's a couple of test to try and help debug this:

1) Do you get an import error if you try `import yaml` in the code which is calling the menu loader?
2) What's the text encoding on the file? I've tried it with ascii and UTF-8; if you're using something else that might be a problem for yaml
3) Could you post a direct copy of the yaml you're trying to load?

**Comment by NicolasCastelli** [comment]
I've tried your possibilities and now I can make it works. I had no import error with `import yaml`, the text encoding was UTF-8, and the yaml content was a copy of your's on the "mGui updates" post. 

But with the #79 branch, it's work perfectly ! With the same yaml file as before, so maybe there just somes issues with the old version.

Thank's for your quick answers, your time and your amazing work !
Best regards

**Comment by theodox** [comment]
Glad it works.  Actually the #79 branch was merged and released as version
2.2 yesterday, it includes a couple of fixes so you might want to
standardize on it

https://github.com/theodox/mGui/releases/tag/2.2
