### ISSUE TITLE
Wrapping optionMenuGrp

### ISSUE THREAD

**Issue by bob-white** [theodox/mGui#86]
Noticed we haven't yet wrapped `cmds.optionMenuGrp`, I was going to do an initial pass on it, but noticed that all of our `MenuGrp` related classes inherit from `Labeled`, which is over in `controls`.

Would it make sense to move `Labeled` over to core? Or should I just import it from `controls`?

**Comment by theodox** [comment]
yeah, I think we can move labeled to core for cleanliness
