### ISSUE TITLE
Heads up on popupmenus

### ISSUE THREAD

**Issue by theodox** [theodox/mGui#87]
I noticed and fixed an issue with mGui 2.2 and popup menus .  The new and improved menu syntax had the side effect of making popups not get added to their owning widgets -- which made them get garbage collected, so any references to themselves (like `kwargs['sender']`) would result in dead reference errors.

I've fixed it already in e8378c0 but if you run into that you may need to catch up on that commit

**Comment by theodox** [comment]
I'll close the issue with the next point release

**Comment by bob-white** [comment]
I had to tweak the shelf_loader a bit with this change, but it looks like that was the only place that relied on the previous behavior.

**Comment by theodox** [comment]
One more change:  I fixed a bug in the menu loader that didn't properly return the parentage of submenus.  Should be good.  Think we're on track for 2.2.1?

**Comment by theodox** [comment]
I'm going to close this issue, I think it's been stable for a while
